bug:

  - "bug"
  - "error"
  - "exception"
  - "crash"

feature:

  - "feature"
  - "enhancement"
  - "new functionality"

documentation:

  - "docs?"
  - "readme"
  - "documentation"

question:

  - "question"
  - "how do i"
  - "help"

tests:

  - "test"
  - "unit test"
  - "integration test"

performance:

  - "slow"
  - "performance"
  - "optimization"
