name: "❓ Question or Support Request"
description: "Ask a question about the project or seek support."
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question? We're here to help! Please be as detailed as possible.
        For bug reports or feature requests, please use the other templates.

  - type: textarea
    id: question
    attributes:
      label: "Your Question"
      description: "Please provide a clear and detailed description of your question."
      placeholder: "How can I use a custom format with the validator? I've tried..."
    validations:
      required: true

  - type: textarea
    id: attempts
    attributes:
      label: "What have you tried?"
      description: "Describe the steps you've already taken to find an answer (e.g., searched the README, checked existing issues)."

  - type: textarea
    id: additional-context
    attributes:
      label: "Additional Context"
      description: "Add any other context, code snippets, or screenshots that might help answer your question."
